services:
  #PHP service container
    laravel_eleven_app:
      platform: linux/amd64
      build: 
        args:
          user: laravel_eleven_user
          uid: 1000
        context: ./
        dockerfile: Dockerfile
      image: laravel_eleven_app_image
      container_name: laravel_eleven_app
      restart: unless-stopped
      working_dir: /var/www
      volumes: 
        - ./:/var/www
      networks:
        - laravel_eleven_app_network
    
    # api:
    #   platform: linux/amd64
    #   build: 
    #     args:
    #       user: laravel_eleven_user
    #       uid: 1000
    #     context: ../kleapi
    #     dockerfile: Dockerfile
    #   image: api_image
    #   container_name: api
    #   restart: unless-stopped
    #   depends_on:
    #     - laravel_eleven_app
    #   working_dir: /var/www
    #   volumes: 
    #     - ./:/var/www
    #   networks:
    #     - laravel_eleven_app_network
      

    #nginx service
    laravel_eleven_webserver:
      platform: linux/amd64
      image: nginx:alpine
      container_name: laravel_eleven_webserver_container
      restart: unless-stopped
      ports:
        -   "80:80"
      depends_on: 
        - laravel_eleven_app
      volumes:
        - ./:/var/www
        - ./docker-compose/nginx/:/etc/nginx/conf.d
        - ./:/node_modules/
        - ./:/public/build/assets
      networks:
        - laravel_eleven_app_network

    laravel_eleven_nodejs:
      platform: linux/amd64
      image: node:22-alpine
      container_name: laravel_eleven_app_nodejs
      restart: no
      depends_on:
        - laravel_eleven_webserver
      volumes:
        - ./:/var/www/
      working_dir: /var/www/
      ports:
        - "7865:7865"
      networks:
        - laravel_eleven_app_network
      command: "npm run build"

networks:
    laravel_eleven_app_network:
        external: true
        name: laravel_eleven_app_network
        driver: bridge
        